import {test} from 'node:test'
import assert from 'node:assert/strict'
import {passwordHash,verifyPassword,sign,readToken} from '../server/auth.js'
import handler from '../api/index.js'
const secret='test-secret-with-at-least-thirty-two-characters'
test('password verification rejects incorrect values',()=>{const hash=passwordHash('test-only-password');assert.ok(verifyPassword('test-only-password',hash));assert.equal(verifyPassword('incorrect',hash),false);assert.equal(verifyPassword('test-only-password','broken'),false)})
test('sessions reject tampering and expiration',()=>{const token=sign({exp:Date.now()+60000},secret);assert.ok(readToken(token,secret));assert.equal(readToken(token+'x',secret),null);assert.equal(readToken(sign({exp:Date.now()-1},secret),secret),null)})
test('catalog and images require session; authenticated image is available',async()=>{process.env.SESSION_SECRET=secret;process.env.RECIPE_PASSWORD_HASH=passwordHash('test-only-password');const run=async(action,cookie='')=>{let status,body;const headers={};await handler({method:'GET',url:`/api?action=${action}`,headers:{cookie}},{setHeader(k,v){headers[k]=v},set statusCode(v){status=v},end(v){body=v}});return {status,body,headers}};for(const action of ['recipes','image&id=01'])assert.equal((await run(action)).status,401);const cookie=`jr_session=${sign({exp:Date.now()+60000,id:'TEST'},secret)}`;const catalog=await run('recipes',cookie);assert.equal(catalog.status,200);assert.equal(JSON.parse(catalog.body).recipes.length,45);assert.equal(JSON.parse(catalog.body).recipes[0].file,undefined);const image=await run('image&id=01',cookie);assert.equal(image.headers['Content-Type'],'image/jpeg');assert.ok(Buffer.isBuffer(image.body));assert.equal((await run('image&id=../../.env.local',cookie)).status,404)})
test('login checks origin and issues HttpOnly cookie',async()=>{process.env.SESSION_SECRET=secret;process.env.RECIPE_PASSWORD_HASH=passwordHash('test-only-password');async function run(origin,password){let status;const headers={};await handler({method:'POST',url:'/api?action=login',headers:{host:'localhost:5173',origin},body:{password},socket:{remoteAddress:'test'}},{setHeader(k,v){headers[k]=v},set statusCode(v){status=v},end(){}});return {status,headers}}assert.equal((await run('https://foreign.test','test-only-password')).status,403);assert.equal((await run('http://localhost:5173','wrong')).status,401);const result=await run('http://localhost:5173','test-only-password');assert.equal(result.status,200);assert.match(result.headers['Set-Cookie'],/HttpOnly; SameSite=Strict/);assert.ok(readToken(result.headers['Set-Cookie'].split(';')[0].split('=')[1],secret))})
