<script setup>
import {ref,computed,onMounted,onBeforeUnmount,nextTick,watch} from 'vue'
const theme=ref(document.documentElement.dataset.theme || 'light')
watch(theme,value=>{document.documentElement.dataset.theme=value;try{localStorage.setItem('jr-theme',value)}catch{}})
const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const categoryIcons={'Desayunos':'☀','Antojitos':'✦','Platos fuertes':'♨','Mariscos':'≈','Frescos':'❋','Postres':'♡'}
const logged=ref(false),loading=ref(true),busy=ref(false),password=ref(''),error=ref(''),recipes=ref([]),category=ref('Todos'),search=ref(''),selected=ref(null),imageUrl=ref(''),watermark=ref(''),hidden=ref(false),zoom=ref(false)
const categories=['Todos','Desayunos','Antojitos','Platos fuertes','Mariscos','Frescos','Postres']
const filtered=computed(()=>recipes.value.filter(r=>(category.value==='Todos'||r.category===category.value)&&normalize(`${r.title} ${r.category}`).includes(normalize(search.value.trim()))))
async function api(action,body){const res=await fetch(`/api?action=${action}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok){if(res.status===401&&action!=='login'){logged.value=false;close()}throw new Error(data.error||'No fue posible completar la solicitud.')}return data}
async function load(){const session=await api('session');watermark.value=session.watermark;recipes.value=(await api('recipes')).recipes;logged.value=true;await nextTick();window.scrollTo(0,0)}
async function login(){busy.value=true;error.value='';try{await api('login',{password:password.value});password.value='';await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function logout(){try{await api('logout',{});logged.value=false;recipes.value=[];close()}catch(e){error.value=e.message}}
let opener=null
async function open(recipe){opener=document.activeElement;close(false);selected.value=recipe;error.value='';try{const res=await fetch(`/api?action=image&id=${recipe.id}`);if(!res.ok){if(res.status===401){logged.value=false;close()}throw new Error('No se pudo abrir la ficha. Vuelve a iniciar sesión.')}imageUrl.value=URL.createObjectURL(await res.blob());await nextTick();document.querySelector('.close')?.focus()}catch(e){error.value=e.message}}
function close(restore=true){if(imageUrl.value)URL.revokeObjectURL(imageUrl.value);imageUrl.value='';selected.value=null;zoom.value=false;if(restore)opener?.focus()}
function visibility(){hidden.value=document.hidden}
function keys(event){if(event.key==='Escape')close();if(selected.value&&event.key==='Tab'){const items=[...document.querySelectorAll('.viewer button')];if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1)?.focus()}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0]?.focus()}}}
onMounted(async()=>{document.addEventListener('visibilitychange',visibility);document.addEventListener('keydown',keys);try{await load()}catch(e){if(!e.message.includes('Inicia sesión'))error.value=e.message}finally{loading.value=false}})
onBeforeUnmount(()=>{close();document.removeEventListener('visibilitychange',visibility);document.removeEventListener('keydown',keys)})
</script>

<template>
 <div class="app" :class="{'privacy-hidden':hidden}" @contextmenu.prevent @dragstart.prevent>
  <header class="site-header">
   <a class="brand" href="/" aria-label="JR Nutrición · Inicio"><span class="brand-logo"><img src="/logo.png" alt="Juan José Rodríguez"></span><span class="brand-name">Tu recetario<span>Ideas para tu día a día</span></span></a>
   <div class="header-actions"><button class="theme-toggle" @click="theme=theme==='dark'?'light':'dark'" :aria-label="theme==='dark'?'Activar modo claro':'Activar modo oscuro'" :title="theme==='dark'?'Activar modo claro':'Activar modo oscuro'"><span aria-hidden="true">{{theme==='dark'?'☀':'☾'}}</span><span class="theme-label">{{theme==='dark'?'Modo claro':'Modo oscuro'}}</span></button><button v-if="logged" class="logout-button" @click="logout">Salir <span aria-hidden="true">↗</span></button><span v-else class="private-tag">Para pacientes</span></div>
  </header>
  <main v-if="!logged" class="login-layout">
   <section class="intro"><p class="eyebrow"><span class="status-dot"></span> NUTRICIÓN QUE TE ACOMPAÑA</p><h1>Comer mejor empieza con una <em>buena idea.</em></h1><p class="intro-copy">¿No sabes qué preparar? Aquí encontrarás recetas prácticas para darle variedad a tus comidas y acompañar tu plan de alimentación.</p><div class="benefit-list"><span><b aria-hidden="true">✓</b> Ideas para cada momento del día</span><span><b aria-hidden="true">✓</b> Ingredientes y preparación en un solo lugar</span><span><b aria-hidden="true">✓</b> Siempre a mano, también en tu celular</span></div><div class="intro-note"><span aria-hidden="true">✦</span><p>Un poco de inspiración.<br><strong>Más confianza en tu cocina.</strong></p></div></section>
   <section class="login-card"><div class="card-icon" aria-hidden="true">↗</div><p class="eyebrow">TU ESPACIO DE RECETAS</p><h2>Bienvenido a tu recetario</h2><p>Usa la contraseña que te compartió tu nutriólogo para comenzar.</p><form @submit.prevent="login"><label for="password">Contraseña de acceso</label><input id="password" v-model="password" type="password" autocomplete="current-password" placeholder="Ingresa tu contraseña" required maxlength="256" :disabled="busy||loading"><p v-if="error" class="error" role="alert">{{error}}</p><button class="primary" :disabled="busy||loading">{{loading?'Cargando…':busy?'Verificando…':'Entrar a mi recetario'}} <span aria-hidden="true">→</span></button></form><div class="login-foot">Acceso exclusivo para pacientes</div></section>
  </main>
  <main v-else class="recipes-layout">
   <section class="welcome-banner"><div class="welcome-copy"><p class="eyebrow"><span class="status-dot"></span> TU INSPIRACIÓN PARA COMER MEJOR</p><h1>¿No sabes qué comer?<br><em>Encuentra una idea aquí.</em></h1><p>Explora recetas, elige lo que se te antoja y consulta cómo prepararlo.</p></div><div class="welcome-aside"><span class="aside-icon" aria-hidden="true">✦</span><strong>{{recipes.length}} ideas</strong><span>para variar tus comidas</span><div class="aside-divider"></div><small>A tu ritmo.<br>Con tu plan en mente.</small></div></section>
   <section class="discovery" aria-label="Encuentra una receta"><label for="recipe-search" class="search-label">¿Qué te gustaría preparar?</label><div class="search-box"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="recipe-search" v-model="search" placeholder="Busca pollo, atún, desayunos…" type="search" autocomplete="off"><button v-if="search" class="clear-search" @click="search=''" aria-label="Limpiar búsqueda">✕</button><span class="search-hint">Encuentra tu próxima comida</span></div><nav class="category-tabs" aria-label="Categorías de recetas"><button v-for="item in categories" :key="item" :class="{active:category===item}" :aria-pressed="category===item" @click="category=item"><span v-if="categoryIcons[item]" aria-hidden="true">{{categoryIcons[item]}}</span>{{item==='Todos'?'Todas las recetas':item}}</button></nav></section>
   <div class="section-heading"><div><p class="eyebrow">IDEAS PARA TU DÍA A DÍA</p><h2>{{search?'Resultados de búsqueda':category==='Todos'?'Elige tu próxima receta':category}}</h2></div><span class="result-count" role="status" aria-live="polite">{{filtered.length}} {{filtered.length===1?'receta':'recetas'}}</span></div><p v-if="error" class="error" role="alert">{{error}}</p>
   <section class="recipe-grid" aria-label="Recetas disponibles"><button v-for="recipe in filtered" :key="recipe.id" class="recipe-card" @click="open(recipe)"><div class="card-top"><span class="recipe-icon" :data-category="recipe.category" aria-hidden="true">{{categoryIcons[recipe.category]}}</span><span class="category-badge">{{recipe.category}}</span></div><h3>{{recipe.title}}</h3><p class="card-description">Consulta los ingredientes y el paso a paso.</p><div class="card-bottom"><span>Ver receta</span><span class="arrow" aria-hidden="true">→</span></div></button></section>
   <div v-if="!filtered.length" class="empty"><span aria-hidden="true">⌕</span><h3>No encontramos una receta con esa búsqueda.</h3><p>Prueba con pollo, huevo o atún, o cambia de categoría.</p><button class="primary" @click="search='';category='Todos'">Explorar todas las recetas →</button></div>
   <aside class="plan-note"><span class="note-icon" aria-hidden="true">✦</span><div><strong>Tu plan de alimentación es tu guía.</strong><p>Elige las recetas y ajusta las porciones según lo que acordaste con tu nutriólogo.</p></div></aside>
  </main>
  <footer><span>JR · Nutrición y bienestar</span><span>Pequeñas decisiones, todos los días.</span></footer>
  <div v-if="selected" class="modal-backdrop" @click.self="close"><section class="viewer" role="dialog" aria-modal="true" aria-labelledby="recipe-title"><div class="viewer-head"><div><p class="eyebrow">{{selected.category}}</p><h2 id="recipe-title">{{selected.title}}</h2></div><button class="close" aria-label="Cerrar receta" @click="close">✕</button></div><div class="viewer-tools"><span>Ingredientes y preparación</span><button @click="zoom=!zoom" :aria-pressed="zoom">{{zoom?'Ajustar ficha':'Ampliar lectura'}} {{zoom?'−':'+'}}</button></div><div class="sheet-scroll"><div v-if="imageUrl" class="protected-sheet" :class="{zoom}"><img :src="imageUrl" :alt="'Ingredientes y preparación de '+selected.title" draggable="false"><div class="watermark" aria-hidden="true"><span v-for="n in 12" :key="n">JR · CONSULTA PRIVADA · {{watermark}}</span></div></div><p v-else class="sheet-loading" role="status">{{error||'Abriendo la receta…'}}</p></div><p class="viewer-foot">Tu recetario personal · Sigue las porciones de tu plan</p></section></div>
 </div><div v-if="hidden" class="privacy-cover">JR · Consulta pausada</div><div class="print-block">Recetario privado · La impresión de las fichas está deshabilitada.</div>
</template>
