<script setup>
import {ref,computed,onMounted,onBeforeUnmount,nextTick} from 'vue'
const logged=ref(false),loading=ref(true),busy=ref(false),password=ref(''),error=ref(''),recipes=ref([]),category=ref('Todos'),search=ref(''),selected=ref(null),imageUrl=ref(''),watermark=ref(''),hidden=ref(false),zoom=ref(false)
const categories=['Todos','Desayunos','Antojitos','Platos fuertes','Mariscos','Frescos','Postres']
const filtered=computed(()=>recipes.value.filter(r=>(category.value==='Todos'||r.category===category.value)&&r.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(search.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())))
async function api(action,body){const res=await fetch(`/api?action=${action}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok){if(res.status===401&&action!=='login'){logged.value=false;close()}throw new Error(data.error||'No fue posible completar la solicitud.')}return data}
async function load(){const session=await api('session');watermark.value=session.watermark;recipes.value=(await api('recipes')).recipes;logged.value=true}
async function login(){busy.value=true;error.value='';try{await api('login',{password:password.value});password.value='';await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function logout(){try{await api('logout',{});logged.value=false;recipes.value=[];close()}catch(e){error.value=e.message}}
let opener=null
async function open(recipe){opener=document.activeElement;close(false);selected.value=recipe;error.value='';try{const res=await fetch(`/api?action=image&id=${recipe.id}`);if(!res.ok){if(res.status===401){logged.value=false;close()}throw new Error('No se pudo abrir la ficha. Vuelve a iniciar sesión.')}imageUrl.value=URL.createObjectURL(await res.blob());await nextTick();document.querySelector('.close')?.focus()}catch(e){error.value=e.message}}
function close(restore=true){if(imageUrl.value)URL.revokeObjectURL(imageUrl.value);imageUrl.value='';selected.value=null;zoom.value=false;if(restore)opener?.focus()}
function visibility(){hidden.value=document.hidden}
function keys(event){if(event.key==='Escape')close();if(selected.value&&event.key==='Tab'){const items=[...document.querySelectorAll('.viewer button')];if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1)?.focus()}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0]?.focus()}}}
onMounted(async()=>{document.addEventListener('visibilitychange',visibility);document.addEventListener('keydown',keys);try{await load()}catch(e){if(!e.message.includes('Inicia sesión'))error.value=e.message}finally{loading.value=false}})
onBeforeUnmount(()=>{close();document.removeEventListener('visibilitychange',visibility);document.removeEventListener('keydown',keys)})
</script>

<template>
 <div class="app" :class="{'privacy-hidden':hidden}" @contextmenu.prevent @dragstart.prevent>
  <header><a class="brand" href="/" aria-label="Recetario JR"><span class="monogram">JR<span>✦</span></span><span>RECETARIO<br><small>COCINA DE CASA</small></span></a><span class="header-note">Hecho para compartir la mesa</span><button v-if="logged" class="text-button" @click="logout">Cerrar sesión ↗</button><span v-else class="private-tag">ACCESO PRIVADO</span></header>
  <main v-if="!logged" class="login-layout">
   <section class="intro"><p class="eyebrow">EL SABOR DE LO COTIDIANO</p><h1>Buenas recetas.<br>Grandes <em>momentos.</em></h1><p class="intro-copy">Una colección de cocina casera para disfrutar, preparar y volver a la mesa.</p><div class="plate-art" aria-hidden="true"><div class="plate"><span class="leaf leaf-one"></span><span class="leaf leaf-two"></span><span class="tomato t1"></span><span class="tomato t2"></span><span class="tomato t3"></span><span class="grain">✦</span></div><span class="art-caption">INGREDIENTES SENCILLOS · SABORES DE SIEMPRE</span></div></section>
   <section class="login-card"><span class="little-star">✦</span><p class="eyebrow">BIENVENIDO A NUESTRA COCINA</p><h2>Tu lugar en la mesa.</h2><p>Ingresa la contraseña para abrir el recetario.</p><form @submit.prevent="login"><label for="password">Contraseña de acceso</label><input id="password" v-model="password" type="password" autocomplete="current-password" placeholder="Escribe tu contraseña" required maxlength="256" :disabled="busy||loading"><p v-if="error" class="error" role="alert">{{error}}</p><button class="primary" :disabled="busy||loading">{{loading?'Preparando la mesa…':busy?'Verificando…':'Abrir el recetario'}} <span>→</span></button></form><div class="login-foot">⌑ &nbsp; Colección privada · Acceso protegido</div></section>
  </main>
  <main v-else class="menu-layout"><section class="menu-heading"><div><p class="eyebrow">LA CARTA DE CASA / EDICIÓN JR</p><h1>¿Qué cocinamos <em>hoy?</em></h1><p>Elige un antojo. Encuentra tu próxima receta favorita.</p></div><div class="collection-count"><strong>{{recipes.length}}</strong><span>FICHAS<br>DE COCINA</span></div></section><div class="menu-tools"><nav aria-label="Secciones del recetario"><button v-for="item in categories" :key="item" :class="{active:category===item}" :aria-pressed="category===item" @click="category=item">{{item}}</button></nav><label class="search"><span aria-hidden="true">⌕</span><input v-model="search" placeholder="Buscar una receta" aria-label="Buscar una receta" type="search"></label></div><div class="section-heading"><h2>{{category==='Todos'?'Nuestra colección':category}}</h2><span>{{filtered.length}} recetas</span></div><p v-if="error" class="error" role="alert">{{error}}</p><section class="recipe-grid"><button v-for="recipe in filtered" :key="recipe.id" class="recipe-card" @click="open(recipe)"><div class="card-top"><span>{{recipe.category}}</span><span class="recipe-number">{{recipe.id}}</span></div><h3>{{recipe.title}}</h3><div class="card-bottom"><span>Ver ficha de preparación</span><span class="arrow">↗</span></div></button></section><div v-if="!filtered.length" class="empty"><h3>No encontramos ese antojo.</h3><p>Prueba otro nombre o explora todas las secciones.</p><button class="text-button" @click="search='';category='Todos'">Ver todas las recetas →</button></div><div class="menu-bottom"><span>✦</span><p>La buena cocina empieza con una buena receta.</p></div></main>
  <footer><span>JR · Recetario de casa</span><span>Preparar. Disfrutar. Repetir.</span></footer>
  <div v-if="selected" class="modal-backdrop" @click.self="close"><section class="viewer" role="dialog" aria-modal="true" aria-labelledby="recipe-title"><div class="viewer-head"><div><p class="eyebrow">{{selected.category}}</p><h2 id="recipe-title">{{selected.title}}</h2></div><button class="close" aria-label="Cerrar receta" @click="close">✕</button></div><div class="viewer-tools"><span>Ficha original · Consulta privada</span><button @click="zoom=!zoom">{{zoom?'Ajustar ficha':'Ampliar lectura'}} {{zoom?'−':'+'}}</button></div><div class="sheet-scroll"><div v-if="imageUrl" class="protected-sheet" :class="{zoom}"><img :src="imageUrl" :alt="`Ingredientes y preparación de ${selected.title}`" draggable="false"><div class="watermark" aria-hidden="true"><span v-for="n in 12" :key="n">JR · CONSULTA PRIVADA · {{watermark}}</span></div></div><p v-else class="sheet-loading" role="status">{{error||'Abriendo la receta…'}}</p></div><p class="viewer-foot">Uso personal · Las fichas incluyen una marca de sesión.</p></section></div>
 </div><div v-if="hidden" class="privacy-cover">JR · Consulta pausada</div><div class="print-block">Recetario privado · La impresión de las fichas está deshabilitada.</div>
</template>
